-- migrate:up

ALTER TABLE nba_games ALTER COLUMN pace TYPE DOUBLE PRECISION;
ALTER TABLE nba_games ALTER COLUMN tov_ratio TYPE DOUBLE PRECISION;
ALTER TABLE nba_games ALTER COLUMN tov_pct TYPE DOUBLE PRECISION;
ALTER TABLE nba_games ALTER COLUMN off_rating TYPE DOUBLE PRECISION;
ALTER TABLE nba_games ALTER COLUMN def_rating TYPE DOUBLE PRECISION;

ALTER TABLE nba_player_stats ALTER COLUMN true_shooting TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN usage_rate TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN reb_pct TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN dreb_pct TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN oreb_pct TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN ast_pct TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN ast_ratio TYPE DOUBLE PRECISION;
ALTER TABLE nba_player_stats ALTER COLUMN tov_ratio TYPE DOUBLE PRECISION;

ALTER TABLE nba_props ALTER COLUMN line TYPE DOUBLE PRECISION;
ALTER TABLE nba_props ALTER COLUMN current_value TYPE DOUBLE PRECISION;

ALTER TABLE users ALTER COLUMN elo_rating TYPE DOUBLE PRECISION;

-- migrate:down

