CREATE TABLE "basketball_player_stats" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"game_id" text NOT NULL,
	"league" "league_type" NOT NULL,
	"fouls" integer DEFAULT 0 NOT NULL,
	"blocks" integer DEFAULT 0 NOT NULL,
	"points" integer DEFAULT 0 NOT NULL,
	"steals" integer DEFAULT 0 NOT NULL,
	"assists" integer DEFAULT 0 NOT NULL,
	"minutes" double precision DEFAULT 0 NOT NULL,
	"turnovers" integer DEFAULT 0 NOT NULL,
	"rebounds" integer DEFAULT 0 NOT NULL,
	"two_points_made" integer DEFAULT 0 NOT NULL,
	"field_goals_made" integer DEFAULT 0 NOT NULL,
	"free_throws_made" integer DEFAULT 0 NOT NULL,
	"three_points_made" integer DEFAULT 0 NOT NULL,
	"defensive_rebounds" integer DEFAULT 0 NOT NULL,
	"offensive_rebounds" integer DEFAULT 0 NOT NULL,
	"two_point_percentage" double precision DEFAULT 0 NOT NULL,
	"two_points_attempted" integer DEFAULT 0 NOT NULL,
	"field_goals_attempted" integer DEFAULT 0 NOT NULL,
	"free_throws_attempted" integer DEFAULT 0 NOT NULL,
	"three_points_attempted" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "basketball_team_stats" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"game_id" text NOT NULL,
	"league" "league_type" NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"fouls" integer DEFAULT 0 NOT NULL,
	"blocks" integer DEFAULT 0 NOT NULL,
	"steals" integer DEFAULT 0 NOT NULL,
	"turnovers" integer DEFAULT 0 NOT NULL,
	"rebounds" integer DEFAULT 0 NOT NULL,
	"two_points_made" integer DEFAULT 0 NOT NULL,
	"field_goals_made" integer DEFAULT 0 NOT NULL,
	"free_throws_made" integer DEFAULT 0 NOT NULL,
	"three_points_made" integer DEFAULT 0 NOT NULL,
	"defensive_rebounds" integer DEFAULT 0 NOT NULL,
	"offensive_rebounds" integer DEFAULT 0 NOT NULL,
	"two_point_percentage" double precision DEFAULT 0 NOT NULL,
	"two_points_attempted" integer DEFAULT 0 NOT NULL,
	"field_goals_attempted" integer DEFAULT 0 NOT NULL,
	"free_throws_attempted" integer DEFAULT 0 NOT NULL,
	"three_points_attempted" integer DEFAULT 0 NOT NULL
);
