CREATE TABLE "football_player_stats" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_id" integer NOT NULL,
	"game_id" text NOT NULL,
	"league" "league_type" NOT NULL,
	"completions" integer DEFAULT 0 NOT NULL,
	"fumbles_lost" integer DEFAULT 0 NOT NULL,
	"rushing_long" integer DEFAULT 0 NOT NULL,
	"passer_rating" double precision DEFAULT 0 NOT NULL,
	"passing_yards" double precision DEFAULT 0 NOT NULL,
	"rushing_yards" double precision DEFAULT 0 NOT NULL,
	"passing_attempts" integer DEFAULT 0 NOT NULL,
	"rushingAttempts" integer DEFAULT 0 NOT NULL,
	"passing_touchdowns" integer DEFAULT 0 NOT NULL,
	"rushing_touchdowns" integer DEFAULT 0 NOT NULL,
	"passing_interceptions" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "football_team_stats" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_id" integer NOT NULL,
	"game_id" text NOT NULL,
	"league" "league_type" NOT NULL,
	"score" integer DEFAULT 0 NOT NULL,
	"sacks" integer DEFAULT 0 NOT NULL,
	"safeties" integer DEFAULT 0 NOT NULL,
	"penalties_total" integer DEFAULT 0 NOT NULL,
	"penalties_yards" integer DEFAULT 0 NOT NULL,
	"turnovers" integer DEFAULT 0 NOT NULL,
	"first_downs" integer DEFAULT 0 NOT NULL,
	"total_plays" integer DEFAULT 0 NOT NULL,
	"total_yards" integer DEFAULT 0 NOT NULL,
	"blocked_kicks" integer DEFAULT 0 NOT NULL,
	"blocked_punts" integer DEFAULT 0 NOT NULL,
	"kicks_blocked" integer DEFAULT 0 NOT NULL,
	"passing_yards" integer DEFAULT 0 NOT NULL,
	"punts_blocked" integer DEFAULT 0 NOT NULL,
	"rushing_yards" integer DEFAULT 0 NOT NULL,
	"dk_fantasy_points" double precision DEFAULT 0 NOT NULL,
	"defense_touchdowns" integer DEFAULT 0 NOT NULL,
	"defense_interceptions" integer DEFAULT 0 NOT NULL,
	"kick_return_touchdowns" integer DEFAULT 0 NOT NULL,
	"punt_return_touchdowns" integer DEFAULT 0 NOT NULL,
	"blocked_kick_touchdowns" integer DEFAULT 0 NOT NULL,
	"blocked_punt_touchdowns" integer DEFAULT 0 NOT NULL,
	"interception_touchdowns" integer DEFAULT 0 NOT NULL,
	"fumble_return_touchdowns" integer DEFAULT 0 NOT NULL,
	"defense_fumble_recoveries" integer DEFAULT 0 NOT NULL,
	"field_goal_return_touchdowns" integer DEFAULT 0 NOT NULL,
	"two_point_conversion_returns" integer DEFAULT 0 NOT NULL,
	"two_point_conversion_attempts" integer DEFAULT 0 NOT NULL,
	"two_point_conversion_succeeded" integer DEFAULT 0 NOT NULL,
	"points_against_defense_special_teams" integer DEFAULT 0 NOT NULL,
	"passing_touchdowns" integer DEFAULT 0 NOT NULL,
	"rushing_touchdowns" integer DEFAULT 0 NOT NULL,
	"special_teams_touchdowns" integer DEFAULT 0 NOT NULL,
	"total_passing_yards_allowed" integer DEFAULT 0 NOT NULL,
	"total_rushing_yards_allowed" integer DEFAULT 0 NOT NULL,
	"offense_touchdowns" integer DEFAULT 0 NOT NULL
);
