ALTER TABLE "baseball_player_stats" ADD CONSTRAINT "fk_player_baseball_player_stats" FOREIGN KEY ("player_id","league") REFERENCES "public"."player"("player_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseball_player_stats" ADD CONSTRAINT "fk_game_baseball_player_stats" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseball_team_stats" ADD CONSTRAINT "fk_team_baseball_team_stats" FOREIGN KEY ("team_id","league") REFERENCES "public"."team"("team_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseball_team_stats" ADD CONSTRAINT "fk_game_baseball_team_stats" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "basketball_player_stats" ADD CONSTRAINT "fk_player_basketball_player_stats" FOREIGN KEY ("player_id","league") REFERENCES "public"."player"("player_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "basketball_player_stats" ADD CONSTRAINT "fk_game_basketball_player_stats" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "basketball_team_stats" ADD CONSTRAINT "fk_team_basketball_team_stats" FOREIGN KEY ("team_id","league") REFERENCES "public"."team"("team_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "basketball_team_stats" ADD CONSTRAINT "fk_game_basketball_team_stats" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "football_player_stats" ADD CONSTRAINT "fk_player_football_player_stats" FOREIGN KEY ("player_id","league") REFERENCES "public"."player"("player_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "football_player_stats" ADD CONSTRAINT "fk_game_football_player_stats" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "football_team_stats" ADD CONSTRAINT "fk_team_football_team_stats" FOREIGN KEY ("team_id","league") REFERENCES "public"."team"("team_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "football_team_stats" ADD CONSTRAINT "fk_game_football_team_stats" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game" ADD CONSTRAINT "fk_home_team_game" FOREIGN KEY ("home_team_id","league") REFERENCES "public"."team"("team_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game" ADD CONSTRAINT "fk_away_team_game" FOREIGN KEY ("away_team_id","league") REFERENCES "public"."team"("team_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "player" ADD CONSTRAINT "fk_team_player" FOREIGN KEY ("team_id","league") REFERENCES "public"."team"("team_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prop" ADD CONSTRAINT "fk_game_prop" FOREIGN KEY ("game_id","league") REFERENCES "public"."game"("game_id","league") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prop" ADD CONSTRAINT "fk_player_prop" FOREIGN KEY ("player_id","league") REFERENCES "public"."player"("player_id","league") ON DELETE cascade ON UPDATE no action;