import express from "express";
import { battlePassRoute } from "./battlePass";
import { friendlyMatchRequestsRoute } from "./friendlyMatchRequests";
import { friendshipsRoute } from "./friendships";
import { gamesRoute } from "./games";
import { matchesRoute } from "./matches";
import { parlaysRoute } from "./parlays";
import { picksRoute } from "./picks";
import { playersRoute } from "./players";
import { propsRoute } from "./props";
import { teamsRoute } from "./teams";
import { usersRoute } from "./users";
import { leaderboardRoute } from "./leaderboard";
import { dynastyLeaguesRoute } from "./dynastyLeagues";

export const routes = express.Router();

routes.use(usersRoute);
routes.use(matchesRoute);
routes.use(propsRoute);
routes.use(parlaysRoute);
routes.use(picksRoute);
routes.use(friendlyMatchRequestsRoute);
routes.use(friendshipsRoute);
routes.use(gamesRoute);
routes.use(teamsRoute);
routes.use(playersRoute);
routes.use(leaderboardRoute);
routes.use(dynastyLeaguesRoute);
routes.use(battlePassRoute);
