/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface NbaGames {
  ast: number | null;
  blk: number | null;
  defRating: Numeric | null;
  dreb: number | null;
  fga: number | null;
  fgm: number | null;
  fta: number | null;
  ftm: number | null;
  gameDate: Timestamp | null;
  gameType: string;
  id: string;
  matchup: string | null;
  min: number | null;
  offRating: Numeric | null;
  oreb: number | null;
  pace: Numeric | null;
  pf: number | null;
  plusMinus: number | null;
  pts: number | null;
  reb: number | null;
  season: string | null;
  stl: number | null;
  teamId: string | null;
  threePa: number | null;
  threePm: number | null;
  tov: number | null;
  tovPct: Numeric | null;
  tovRatio: Numeric | null;
  wl: string | null;
}

export interface NbaPlayers {
  height: string | null;
  id: string;
  name: string | null;
  number: string | null;
  position: string | null;
  teamId: string | null;
  updatedAt: Generated<Timestamp | null>;
  weight: string | null;
}

export interface NbaPlayerStats {
  ast: number | null;
  astPct: Numeric | null;
  astRatio: Numeric | null;
  blk: number | null;
  dreb: number | null;
  drebPct: Numeric | null;
  fga: number | null;
  fgm: number | null;
  fta: number | null;
  ftm: number | null;
  gameId: string | null;
  id: string;
  min: number | null;
  oreb: number | null;
  orebPct: Numeric | null;
  pf: number | null;
  playerId: string | null;
  plusMinus: number | null;
  pts: number | null;
  reb: number | null;
  rebPct: Numeric | null;
  season: string | null;
  stl: number | null;
  threePa: number | null;
  threePm: number | null;
  tov: number | null;
  tovRatio: Numeric | null;
  trueShooting: Numeric | null;
  updatedAt: Generated<Timestamp | null>;
  usageRate: Numeric | null;
}

export interface NbaProps {
  createdAt: Generated<Timestamp | null>;
  currentValue: Numeric | null;
  gameStartTime: Timestamp | null;
  id: Generated<string>;
  line: Numeric;
  playerId: string;
  rawGameId: string;
  statType: string;
}

export interface NbaTeams {
  abbreviation: string | null;
  city: string | null;
  fullName: string | null;
  id: string;
  nickname: string | null;
  state: string | null;
  yearFounded: number | null;
}

export interface SchemaMigrations {
  version: string;
}

export interface Users {
  createdAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<string>;
  image: string | null;
  name: string | null;
  passwordHash: string;
  username: string;
}

export interface DB {
  nbaGames: NbaGames;
  nbaPlayers: NbaPlayers;
  nbaPlayerStats: NbaPlayerStats;
  nbaProps: NbaProps;
  nbaTeams: NbaTeams;
  schemaMigrations: SchemaMigrations;
  users: Users;
}
