/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Matches {
  created_at: Generated<Timestamp | null>;
  ends_at: Timestamp;
  id: Generated<string>;
  resolved: Generated<boolean | null>;
}

export interface MatchUserNbaPicks {
  id: Generated<string>;
  match_user_id: string | null;
  nba_prop_id: string | null;
  pick: string;
}

export interface MatchUsers {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  match_id: string | null;
  user_id: string | null;
}

export interface NbaGames {
  ast: number | null;
  blk: number | null;
  def_rating: number | null;
  dreb: number | null;
  fga: number | null;
  fgm: number | null;
  fta: number | null;
  ftm: number | null;
  game_date: Timestamp | null;
  game_type: string;
  id: string;
  matchup: string | null;
  min: number | null;
  off_rating: number | null;
  oreb: number | null;
  pace: number | null;
  pf: number | null;
  plus_minus: number | null;
  pts: number | null;
  reb: number | null;
  season: string | null;
  stl: number | null;
  team_id: string | null;
  three_pa: number | null;
  three_pm: number | null;
  tov: number | null;
  tov_pct: number | null;
  tov_ratio: number | null;
  wl: string | null;
}

export interface NbaPlayers {
  height: string | null;
  id: string;
  name: string | null;
  number: string | null;
  position: string | null;
  team_id: string | null;
  updated_at: Generated<Timestamp | null>;
  weight: string | null;
}

export interface NbaPlayerStats {
  ast: number | null;
  ast_pct: number | null;
  ast_ratio: number | null;
  blk: number | null;
  dreb: number | null;
  dreb_pct: number | null;
  fga: number | null;
  fgm: number | null;
  fta: number | null;
  ftm: number | null;
  game_id: string | null;
  id: string;
  min: number | null;
  oreb: number | null;
  oreb_pct: number | null;
  pf: number | null;
  player_id: string | null;
  plus_minus: number | null;
  pts: number | null;
  reb: number | null;
  reb_pct: number | null;
  season: string | null;
  stl: number | null;
  three_pa: number | null;
  three_pm: number | null;
  tov: number | null;
  tov_ratio: number | null;
  true_shooting: number | null;
  updated_at: Generated<Timestamp | null>;
  usage_rate: number | null;
}

export interface NbaProps {
  created_at: Generated<Timestamp | null>;
  current_value: number | null;
  game_start_time: Timestamp | null;
  id: Generated<string>;
  line: number;
  player_id: string;
  raw_game_id: string;
  stat_type: string;
}

export interface NbaTeams {
  abbreviation: string | null;
  city: string | null;
  full_name: string | null;
  id: string;
  nickname: string | null;
  state: string | null;
  year_founded: number | null;
}

export interface SchemaMigrations {
  version: string;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  elo_rating: Generated<number>;
  email: string;
  id: Generated<string>;
  image: string | null;
  is_bot: boolean | null;
  name: string | null;
  password_hash: string;
  username: string;
}

export interface DB {
  match_user_nba_picks: MatchUserNbaPicks;
  match_users: MatchUsers;
  matches: Matches;
  nba_games: NbaGames;
  nba_player_stats: NbaPlayerStats;
  nba_players: NbaPlayers;
  nba_props: NbaProps;
  nba_teams: NbaTeams;
  schema_migrations: SchemaMigrations;
  users: Users;
}
